### ISSUE TITLE
[Suggestion] IC2 Classic support

### ISSUE THREAD

**Issue by xJon** [ShadowKing21228/Thaumcraft-Integration#2]
Does not always utilise ore dictionary, but also examples such as `Rubber Wood` utilise `woodRubber` which is unsupported currently.

**Comment by ShadowKing21228** [comment]
Ok, I add it to next mod update. 
woodRubber
and itemRawRubber (check [table](https://docs.google.com/spreadsheets/d/1Ytp25U5-H3lQR9Co3NFsl0lk4EVEQQBfl7K0ZvDhYt8/edit?usp=sharing))
And I do direct integrations to IC2E/IC2C later.

**Comment by xJon** [comment]
@ShadowKing21228 Also `foodFlour` support would be appreciated!

**Comment by ShadowKing21228** [comment]
> @ShadowKing21228 Also `foodFlour` support would be appreciated!

Done
