### ISSUE TITLE
[Suggestion] Binnie's Extra Trees fruit support

### ISSUE THREAD

**Issue by xJon** [ShadowKing21228/Thaumcraft-Integration#3]
Would be really nice to have aspects on fruit (e.g. `listAllcitrus` or `cropOrange`) and their respective Juice Buckets/Bottles/Fluids (e.g. `foodOrangejuice`).

**Comment by ShadowKing21228** [comment]
To be honest, I don't want to make aspects of each crop Oredict, but if you want, you can make a copy of my table with them and I'll add them.
`listAllfruit` has already been added

**Comment by xJon** [comment]
@ShadowKing21228 `listAllfruit` is great, perhaps also utilise `listAllcitrus`, `listAllberry`, `listAllnut`, `listAllpepper` (used by `Chilli`) & `listAllspice` and call it a day?
