### ISSUE TITLE
Expand oredict support to more type of parts for all material

### ISSUE THREAD

**Issue by ghost** [ShadowKing21228/Thaumcraft-Integration#5]
The reason I bring this up is that I found that Osmium Ingots have the element, but Osmium Plates (from More Plates mod) do not, which is very important when there are mods like JAOPCA.
Example:plate,gear,rod(stick),densePlate,dust

Also some mod material support requests:ActuallyAdditions,NaturesAura,BloodMagic,NuclearCraftOverhauled,IndustrailForegoing,Calculator
RedstoneArsenal,RedstoneRepositoryRevolved(both Thermal Expanation addons)

**Comment by ShadowKing21228** [comment]
Adding support for other types of items from the same material is indeed a good idea, I haven't added this before as only a few mods take advantage of such variations. 
I will take your wishes into account in the integration.
Blood Magic already has integration.

**Comment by ShadowKing21228** [comment]
I did what you asked about the different types of metals in the new version 1.1, you can read more in the changelog and [here](https://docs.google.com/spreadsheets/d/1Ytp25U5-H3lQR9Co3NFsl0lk4EVEQQBfl7K0ZvDhYt8/edit?usp=sharing).

**Comment by ghost** [comment]
Thanks
